In [1]:
import pandas as pd

In [2]:
file = '/Users/andysheung/Appcara/DL Data/Dec 30/Renamed csv/Dec 30_Test 3.csv'
df = pd.read_csv(file)
df

,TIME,01_Temp(oC),01_RH(%),02_Temp(oC),02_RH(%),03_Temp(oC),03_RH(%),04_Temp(oC),04_RH(%),05_Temp(oC),...,95_Temp(oC),95_RH(%),96_Temp(oC),96_RH(%),97_Temp(oC),97_RH(%),98_Temp(oC),98_RH(%),99_Temp(oC),99_RH(%)
0,2024-12-30 15:20:00,32.9,34.8,NaN,NaN,23.3,50.3,33.7,32.3,36.1,...,18.7,61.9,20.1,58.6,25.6,44.8,21.2,54.9,19.6,60.1
1,2024-12-30 15:21:00,32.9,34.8,NaN,NaN,23.3,50.3,33.7,32.3,36.1,...,18.6,62.1,20.0,59.1,25.6,44.9,21.1,55.1,19.6,60.1
2,2024-12-30 15:22:00,32.8,34.9,NaN,NaN,23.2,50.4,33.8,32.4,36.1,...,18.7,61.9,20.7,57.9,25.5,45.1,21.2,55.2,19.6,60.1
3,2024-12-30 15:23:00,32.7,35.1,NaN,NaN,23.3,50.5,33.7,32.4,36.1,...,18.6,62.1,22.2,54.5,25.4,45.3,21.2,55.1,19.6,60.1
4,2024-12-30 15:24:00,32.6,35.2,NaN,NaN,23.3,50.5,33.7,32.4,36.1,...,18.7,61.8,23.2,52.2,25.3,45.4,21.2,55.2,19.6,60.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,2024-12-30 17:46:00,29.1,40.3,NaN,NaN,23.5,50.5,34.0,32.4,36.7,...,18.6,62.5,22.3,54.5,25.5,45.8,21.2,55.8,19.7,60.7
147,2024-12-30 17:47:00,29.1,40.3,NaN,NaN,23.5,50.5,34.0,32.4,36.7,...,18.7,62.2,22.2,54.3,25.5,45.7,21.2,55.8,19.7,60.7
148,2024-12-30 17:48:00,29.1,40.3,NaN,NaN,23.6,50.4,34.0,32.4,36.7,...,18.7,62.5,20.9,57.2,25.6,45.5,21.2,55.9,19.7,60.7
149,2024-12-30 17:49:00,29.1,40.3,NaN,NaN,23.5,50.4,34.0,32.3,36.7,...,18.7,62.2,20.8,57.8,25.6,45.5,21.2,55.8,19.7,60.6
150,2024-12-30 17:50:00,29.0,40.5,NaN,NaN,23.5,50.4,34.0,32.4,36.7,...,18.7,62.4,20.6,58.2,25.6,45.5,21.3,55.6,19.7,60.6

In [6]:
import pandas as pd
import json

# Read the JSON file
with open('/Users/andysheung/Appcara/DL Data/dl_arr.json', 'r') as file:
    dl_data = json.load(file)

# Assuming df is your Pandas DataFrame

# Calculate the average temperature for the last 1 hour
#df['Average_Temp'] = df.filter(like='_Temp').mean(axis=1)
print(df)
# Define the racks and aisles for the table
racks = {
    "Heater rack": ["Heater rack - Cold aisle", "Heater rack - Hot aisle(left)", "Heater rack - Hot aisle(right)"],
    "Normal rack": ["Normal rack - Cold aisle", "Normal rack - Hot aisle(left)", "Normal rack - Hot aisle(right)"]
}

aisles = ["top", "mid", "low"]

# Create a dictionary to store the average temperatures for each rack and aisle
average_temps = []

for rack_type, rack_names in racks.items():
    for rack_name in rack_names:
        for i, aisle in enumerate(aisles):
            key = f"{rack_type} - {aisle}"
            dl_numbers = dl_data.get(rack_name)[i]
            temps = df.loc[df.index.isin(dl_numbers), 'Average_Temp']
            average_temp = temps.mean() if not temps.empty else 0
            average_temps.append((key, round(average_temp, 2)))

# Print or use the list of average temperatures
#print(average_temps)

                    TIME  01_Temp(oC)  01_RH(%)  02_Temp(oC)  02_RH(%)  \
0    2024-12-30 15:20:00         32.9      34.8          NaN       NaN
1    2024-12-30 15:21:00         32.9      34.8          NaN       NaN
2    2024-12-30 15:22:00         32.8      34.9          NaN       NaN
3    2024-12-30 15:23:00         32.7      35.1          NaN       NaN
4    2024-12-30 15:24:00         32.6      35.2          NaN       NaN
..                   ...          ...       ...          ...       ...
146  2024-12-30 17:46:00         29.1      40.3          NaN       NaN
147  2024-12-30 17:47:00         29.1      40.3          NaN       NaN
148  2024-12-30 17:48:00         29.1      40.3          NaN       NaN
149  2024-12-30 17:49:00         29.1      40.3          NaN       NaN
150  2024-12-30 17:50:00         29.0      40.5          NaN       NaN

     03_Temp(oC)  03_RH(%)  04_Temp(oC)  04_RH(%)  05_Temp(oC)  ...  95_RH(%)  \
0           23.3      50.3         33.7      32.3         36.1  ...      61.9
1           23.3      50.3         33.7      32.3         36.1  ...      62.1
2           23.2      50.4         33.8      32.4         36.1  ...      61.9
3           23.3      50.5         33.7      32.4         36.1  ...      62.1
4           23.3      50.5         33.7      32.4         36.1  ...      61.8
..           ...       ...          ...       ...          ...  ...       ...
146         23.5      50.5         34.0      32.4         36.7  ...      62.5
147         23.5      50.5         34.0      32.4         36.7  ...      62.2
148         23.6      50.4         34.0      32.4         36.7  ...      62.5
149         23.5      50.4         34.0      32.3         36.7  ...      62.2
150         23.5      50.4         34.0      32.4         36.7  ...      62.4

     96_Temp(oC)  96_RH(%)  97_Temp(oC)  97_RH(%)  98_Temp(oC)  98_RH(%)  \
0           20.1      58.6         25.6      44.8         21.2      54.9
1           20.0      59.1         25.6      44.9         21.1      55.1
2           20.7      57.9         25.5      45.1         21.2      55.2
3           22.2      54.5         25.4      45.3         21.2      55.1
4           23.2      52.2         25.3      45.4         21.2      55.2
..           ...       ...          ...       ...          ...       ...
146         22.3      54.5         25.5      45.8         21.2      55.8
147         22.2      54.3         25.5      45.7         21.2      55.8
148         20.9      57.2         25.6      45.5         21.2      55.9
149         20.8      57.8         25.6      45.5         21.2      55.8
150         20.6      58.2         25.6      45.5         21.3      55.6

     99_Temp(oC)  99_RH(%)  Average_Temp
0           19.6      60.1     24.728235
1           19.6      60.1     24.720000
2           19.6      60.1     24.734118
3           19.6      60.1     24.755294
4           19.6      60.1     24.774118
..           ...       ...           ...
146         19.7      60.7     24.531765
147         19.7      60.7     24.528235
148         19.7      60.7     24.501176
149         19.7      60.6     24.489412
150         19.7      60.6     24.470588

[151 rows x 198 columns]